/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime false` (hash: 88e800bc8b234414b98d47b6f738568a)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker");
		durableNamespaces: "ChatSessionDurableObject" | "BrowserSessionDurableObject" | "ProviderUserContextDurableObject" | "AccountRegistryDurableObject";
	}
	interface Env {
		AI: Ai;
		ASSETS: Fetcher;
		OPENROUTER_API_KEY: string;
		OPENROUTER_MODEL: string;
		OPENROUTER_SITE_URL: string;
		OPENROUTER_SITE_NAME: string;
		TEXTY_USE_WORKERS_AI_ROUTING: string;
		BROWSER_SESSIONS: DurableObjectNamespace<import("./src/worker").BrowserSessionDurableObject>;
		CHAT_SESSIONS: DurableObjectNamespace<import("./src/worker").ChatSessionDurableObject>;
		PROVIDER_USER_CONTEXTS: DurableObjectNamespace<import("./src/worker").ProviderUserContextDurableObject>;
		ACCOUNT_REGISTRY: DurableObjectNamespace<import("./src/worker").AccountRegistryDurableObject>;
	}
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "OPENROUTER_API_KEY" | "OPENROUTER_MODEL" | "OPENROUTER_SITE_URL" | "OPENROUTER_SITE_NAME" | "TEXTY_USE_WORKERS_AI_ROUTING">> {}
}
